=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_6/inventario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="inventario">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipo" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tipo" minOccurs="1" maxOccurs="1" type="tipoEquipo" />
							<xs:element name="numserie" minOccurs="1" maxOccurs="1" type="xs:string" />
							<xs:element name="fechaadquisicion" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dia" minOccurs="1" maxOccurs="1" type="tipoDia" />
										<xs:element name="mes" minOccurs="1" maxOccurs="1" type="tipoMes" />
										<xs:element name="year" minOccurs="1" maxOccurs="1" type="tipoYear" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="ubicacion" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="departamento" minOccurs="1" maxOccurs="1" type="xs:string" />
										<xs:element name="aula" minOccurs="1" maxOccurs="1" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="caracteristicas" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fabricante" minOccurs="1" maxOccurs="1" type="xs:string" />
										<xs:element name="modelo" minOccurs="1" maxOccurs="1" type="xs:string" />
										<xs:element name="memoria" minOccurs="0" maxOccurs="1" type="xs:string" />
										<xs:element name="disco" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="discotipo" minOccurs="1" maxOccurs="1" type="xs:string" />
													<xs:element name="capacidad" minOccurs="1" maxOccurs="1" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="procesador" minOccurs="0" maxOccurs="1" type="xs:string" />
										<xs:element name="tipoimpresion" minOccurs="0" maxOccurs="1" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="idequip" use="required" type="tipoId" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoId">
		<xs:restriction base="xs:string">
			<xs:pattern value="(eq3900080)[0-9]{3}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoEquipo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CPU_Torre"></xs:enumeration>
			<xs:enumeration value="Impresora"></xs:enumeration>
			<xs:enumeration value="Monitor"></xs:enumeration>
			<xs:enumeration value="Portatil"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoDia">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"></xs:minInclusive>
			<xs:maxInclusive value="31"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoMes">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"></xs:minInclusive>
			<xs:maxInclusive value="12"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoYear">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1996"></xs:minInclusive>
			<xs:maxInclusive value="2100"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_6/inventario.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="inventario.xsd">
	<!-- El xml original tenia el idequip de esta forma 3900080001
		y por lo tanto no sigue el patron que requiere el XSD ya que es
		(eq3900080)[0-9]{3}-->
    <equipo idequip="eq3900080001">
        <tipo>CPU_Torre</tipo>
		<numserie>DL3996626F33</numserie>
        <fechaadquisicion>
			<dia>12</dia>
			<mes>3</mes>
			<year>2021</year>
		</fechaadquisicion>
		<ubicacion>
			<departamento>Informática y Comunicaciones</departamento>
			<aula>A31</aula>
		</ubicacion>
		<caracteristicas>
			<fabricante>DELL</fabricante>
			<modelo>Inspiron Small Desktop</modelo>
			<memoria>8GB</memoria>
			<disco>
				<discotipo>SSD</discotipo>
				<capacidad>512GB</capacidad>
			</disco>
			<procesador>Intel Core i7 - 10700F</procesador>
		</caracteristicas>
      </equipo>  
	  <equipo idequip="eq3900080002">
        <tipo>Impresora</tipo>
		<numserie>HP78664543</numserie>
        <fechaadquisicion>
			<dia>16</dia>
			<mes>1</mes>
			<year>2022</year>
		</fechaadquisicion>
		<ubicacion>
			<departamento>Administración y Gestión</departamento>
			<aula>A27</aula>
		</ubicacion>
		<caracteristicas>
			<fabricante>HP</fabricante>
			<modelo>DeskJet 2721e</modelo>
			<tipoimpresion>Tinta</tipoimpresion>
		</caracteristicas>
      </equipo>  
</inventario>
