=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio8/bar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ordenes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="consumicion" minOccurs="1" maxOccurs="6" type="TipoConsumicion" />
                            <xs:element name="precio" type="TipoPrecio"/>
                            <xs:element name="nombre" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="TipoID"/>
                        <xs:attribute name="fecha" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TipoID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[T][0-9][0-9][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TipoConsumicion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Refresco"></xs:enumeration>
            <xs:enumeration value="Copa"></xs:enumeration>
            <xs:enumeration value="Vino"></xs:enumeration>
            <xs:enumeration value="Cafe"></xs:enumeration>
            <xs:enumeration value="Tapa"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TipoPrecio">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([0-9]*([.][0-9]{2})?[â‚¬])|([0-9]*([.][0-9]{2})?[$]))"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio8/bar.xml
<?xml version="1.0" encoding="UTF-8"?>
<ordenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="bar.xsd">
    <ticket id="T300" fecha="2023-12-02">
        <consumicion>Refresco</consumicion>
        <consumicion>Cafe</consumicion>
        <consumicion>Tapa</consumicion>
        <precio>12$</precio>
        <nombre>Juan</nombre>
    </ticket>
    <ticket id="T301" fecha="2023-12-02">
        <consumicion>Refresco</consumicion>
        <precio>18â‚¬</precio>
        <nombre>Juan</nombre>
    </ticket>
</ordenes>
