=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/PRACTICASGUIADAS/Practica2/Biblioteca.dtd
<!ELEMENT biblioteca (personal,libros,socios)>
    <!ELEMENT personal (empleado+)>
        <!ELEMENT empleado (nombre,apellidos,telefono,dni,fcontratacion,puesto)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellidos (#PCDATA)>
            <!ELEMENT telefono (#PCDATA)>
            <!ELEMENT dni (#PCDATA)>
            <!ELEMENT fcontratacion (dia,mes,anio)>
                <!ELEMENT dia (#PCDATA)>
                <!ELEMENT mes (#PCDATA)>
                <!ELEMENT anio (#PCDATA)>
            <!ELEMENT puesto (#PCDATA)>
    <!ELEMENT libros (libro+)>
        <!ELEMENT libro (titulo,autor,copias)>
        <!ATTLIST libro id ID #REQUIRED>
            <!ELEMENT titulo (#PCDATA)>
            <!ELEMENT autor (#PCDATA)>
            <!ELEMENT copias (#PCDATA)>
    <!ELEMENT socios (socio+)>
        <!ELEMENT socio (nombre,apellidos,telefono,dni,librosprestados)>
        <!ATTLIST socio num NMTOKEN #REQUIRED>
           <!ELEMENT librosprestados (libroprestado*)> 
           <!ELEMENT libroprestado EMPTY>
           <!ATTLIST libroprestado id IDREF #REQUIRED>
           <!ATTLIST libroprestado fecha CDATA #REQUIRED>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/PRACTICASGUIADAS/Practica2/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE biblioteca PUBLIC "public-id" "Biblioteca.dtd">
<biblioteca>
	<personal>
		<empleado>
			<nombre>Amancio</nombre>
			<apellidos>Rodriguez Perez</apellidos>
			<telefono>123456789</telefono>
			<dni>112223333-C</dni>
			<fcontratacion>
				<dia>9</dia>
				<mes>12</mes>
				<anio>2001</anio>
			</fcontratacion>
			<puesto>Encargado</puesto>
		</empleado>
	</personal>
	<libros>
		<libro id="a1">
			<titulo>Se√±ales y Sistemas</titulo>
			<autor>Alan V. Opennheim</autor>
			<copias>25</copias>
		</libro>
	</libros>
	<socios>
		<socio num="123-abc">
			<nombre>Estela</nombre>
			<apellidos>Sanchez Fernandez</apellidos>
			<telefono>987654321</telefono>
			<dni>44555666-D</dni>
			<librosprestados>
				<libroprestado id="a1" fecha="29/9/2021"/>
			</librosprestados>			
		</socio>
	</socios>
</biblioteca>
