=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.7 Validar un documento XML mediante XSD/Videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="videoclub">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="peliculas" ></xs:element>
				<xs:element ref="videojuegos" ></xs:element>
				<xs:element ref="comidas" ></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="peliculas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pelicula" minOccurs="1"  maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="anio" type="xs:integer" />
							<xs:element name="cantidad" type="xs:integer" />
							<xs:element name="duracion" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="titulo" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videojuegos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="videojuego" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="distribuidor" type="xs:string" />
							<xs:element name="anio" type="xs:integer" />
							<xs:element name="genero" type="xs:string" />
							<xs:element name="plataformas">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="plataforma" minOccurs="1" maxOccurs="unbounded" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="nombre" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comidas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="comida">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="producto" type="xs:string" />
							<xs:element name="stock" type="xs:string" />
							<xs:element name="proveedor" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.7 Validar un documento XML mediante XSD/Videoclub.xml
<?xml version="1.0" encoding="UTF-8" ?>
<videoclub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Videoclub.xsd">
	
	<peliculas>
		<pelicula titulo="El resplandor">
			<anio>1980</anio>
			<cantidad>10</cantidad>
			<duracion>146 minutos</duracion>
		</pelicula>
        
		<pelicula titulo="Zombies Party">
			<anio>2004</anio>
			<cantidad>5</cantidad>
			<duracion>99 minutos</duracion>
		</pelicula>
	</peliculas>
    
	<videojuegos>

		<videojuego nombre="GTA V">
			<distribuidor>Rockstar Games</distribuidor>
			<anio>2013</anio>
			<genero>Acción / Mundo abierto</genero>
			<plataformas>
				<plataforma>PS4</plataforma>
				<plataforma>PC</plataforma>
				<plataforma>Xbox 360</plataforma>
			</plataformas>
		</videojuego>

		<videojuego nombre="Red Dead Redemtion 2">
			<distribuidor>Rockstar Games</distribuidor>
			<anio>2018</anio>
			<genero>Acción / Mundo abierto / Oeste americano</genero>
			<plataformas>
				<plataforma>PS4</plataforma>
				<plataforma>Xbox 360</plataforma>
			</plataformas>
		</videojuego>

		<videojuego nombre="Diablo">
			<distribuidor>Blizzard North</distribuidor>
			<anio>2005</anio>
			<genero>Rol</genero>
			<plataformas>
				<plataforma>PC</plataforma>
			</plataformas>
		</videojuego>

	</videojuegos>

	<comidas>
		<comida>
			<producto>Manzana</producto>
			<stock>20 Kg</stock>
			<proveedor>Fruteria Paco</proveedor>
		</comida>
	</comidas>
	
</videoclub>
