=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio6/floristeria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flor" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" maxOccurs="1" type="xs:string" />
                            <xs:element name="temporada" maxOccurs="1" type="TipoTemporada" />
                            <xs:element name="color" minOccurs="1" maxOccurs="4" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="precio" use="required" type="TipoPrecio" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="TipoPrecio">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]*([.][0-9]{2})?[€]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoTemporada">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Primavera"></xs:enumeration>
            <xs:enumeration value="Verano"></xs:enumeration>
            <xs:enumeration value="Otoño"></xs:enumeration>
            <xs:enumeration value="Invierno"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio6/floristeria.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="floristeria.xsd">
    <flor precio="12€">
        <nombre>Orquidea</nombre>
        <temporada>Primavera</temporada>
        <color>Rojo</color>
        <color>Rosa</color>
    </flor>
    <flor precio="20000.00€">
        <nombre>Rosa</nombre>
        <temporada>Verano</temporada>
        <color>Rojo</color>
    </flor>
</catalogo>
