=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio4/tienda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dependiente" type="xs:string" />
                            <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded"  type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required" />
                        <xs:attribute name="tienda" type="xs:string" use="required" />
                        <xs:attribute name="fecha" type="xs:date" />
                        <xs:attribute name="hora" type="xs:time" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio4/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="tienda.xsd">
    <ticket id="m01" tienda="Zara" fecha="2023-02-02" hora="19:00:00">
        <dependiente>Albano</dependiente>
        <articulo>Americana</articulo>
        <articulo>Sudadera</articulo>
        <articulo>Pantalon</articulo>
    </ticket>
    <ticket id="m02" tienda="Primark" fecha="2023-01-01" hora="20:00:00">
        <dependiente>Juan</dependiente>
        <articulo>Americana</articulo>
    </ticket>
</tienda>
