=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/PRACTICASGUIADAS/Practica3/AG4.3_DTD_Listado.dtd
<!ELEMENT listado (asignaturas,profesores,cursos)>
    <!ELEMENT asignaturas (asignatura*)>
        <!ELEMENT asignatura ((nombre, num_horas)|(num_horas,nombre))>
        <!ATTLIST asignatura prof IDREF #REQUIRED>
        <!ATTLIST asignatura curso IDREF #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT num_horas (#PCDATA)>
    <!ELEMENT profesores (profesor*)>
        <!ELEMENT profesor (nombre, apellidos,tutor?)>
        <!ATTLIST profesor id ID #REQUIRED>
        <!ATTLIST profesor sexo (Hombre|Mujer) #REQUIRED>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT tutor EMPTY>
    <!ELEMENT cursos (curso*)>
        <!ELEMENT curso (nivel,grupo)>
        <!ATTLIST curso id ID #REQUIRED>
        <!ELEMENT nivel (#PCDATA)>
        <!ELEMENT grupo (#PCDATA)>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/PRACTICASGUIADAS/Ficheros para prácticas guiadas/Listado.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE listado SYSTEM "./AG4.3_DTD_Listado.dtd">
<listado>
    
    <asignaturas>
        <asignatura prof="AFD" curso="E4A">
            <nombre>Historia</nombre>
            <num_horas>4</num_horas>
        </asignatura>
        <asignatura prof="AFD" curso="E4B">
            <num_horas>4</num_horas>
            <nombre>Historia</nombre>
        </asignatura>
        <asignatura prof="CHL" curso="E4A">
            <num_horas>3</num_horas>
            <nombre>Biologia</nombre>
        </asignatura>
        <asignatura prof="CST" curso="E4A">
            <nombre>Matematicas</nombre>
            <num_horas>5</num_horas>
        </asignatura>
        <asignatura prof="CHL" curso="E4B">
            <nombre>Biologia</nombre>
            <num_horas>3</num_horas>
        </asignatura>
    </asignaturas>

    <profesores>
        <profesor id="AFD" sexo="Hombre">
            <nombre>Antonio</nombre>
            <apellidos>Fernandez Diaz</apellidos>
            <tutor />
        </profesor>
        <profesor id="CST" sexo="Mujer">
            <nombre>Carmen</nombre>
            <apellidos>Sanchez Torres</apellidos>
        </profesor>
        <profesor id="CHL" sexo="Mujer">
            <nombre>Cristina</nombre>
            <apellidos>Hernandez Lopez</apellidos>
            <tutor />
        </profesor>
    </profesores>
    
    <cursos>
        <curso id="E4A">
            <nivel>4º ESO</nivel>
            <grupo>A</grupo>
        </curso>
        <curso id="E4B">
            <nivel>4º ESO</nivel>
            <grupo>B</grupo>
        </curso>
        <curso id="B1T">
            <nivel>1º BACHILLER</nivel>
            <grupo>Tecnologico</grupo>
        </curso>
        <curso id="B1A">
            <nivel>1º BACHILLER</nivel>
            <grupo>Artes</grupo>
        </curso>
        <curso id="B2T">
            <nivel>2º BACHILLER</nivel>
            <grupo>Tecnologico</grupo>
        </curso>
        <curso id="B2A">
            <nivel>2º BACHILLER</nivel>
            <grupo>Artes</grupo>
        </curso>
    </cursos>
</listado>
