=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.8 Validar un documento XML mediante XSD/Discografica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="discografica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grupos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="grupo" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="componentes" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="componente" minOccurs="3" maxOccurs="6">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="instrumento" type="xs:string"></xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="discos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="disco" minOccurs="0" maxOccurs="5">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="orden" type="xs:unsignedInt"></xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name="nombre" type="xs:string"></xs:attribute>
                                    <xs:attribute name="estilo" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.8 Validar un documento XML mediante XSD/Discografica.xml
<?xml version='1.0' encoding='UTF-8' ?>
<discografica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Discografica.xsd">
    <grupos>
        <grupo nombre="Metallica" estilo="Trash Metal">
            <componentes>
                <componente instrumento="Voz y Guitarra">James Hetfield</componente>
                <componente instrumento="Bateria">Lars Ulrich</componente>
                <componente instrumento="Bajo">Robert Trujillo</componente>
                <componente instrumento="Guitarra">Kirk Hammett</componente>
            </componentes>
            <discos>
                <disco orden="1">Kill'Em All</disco>
                <disco orden="2">Ride The Lightning</disco>
                <disco orden="3">Master of Puppets</disco>
                <disco orden="4">...And Justice For All</disco>
                <disco orden="5">Metallica</disco>
            </discos>
        </grupo>
        <grupo nombre="Pearl Jam" estilo="RocK'n'Roll">
            <discos>
                <disco orden="1">Ten</disco>
                <disco orden="2">Vs.</disco>
                <disco orden="3">Vitalogy</disco>
            </discos>
            <componentes>
                <componente instrumento="Voz">Eddie Vedder</componente>
                <componente instrumento="Guitarra">Mike McCready</componente>
                <componente instrumento="Guitarra">Stone Gossard</componente>
                <componente instrumento="Bajo">Jeff Ament</componente>
                <componente instrumento="Bateria">Matt Cameron</componente>
                <componente instrumento="Teclado">Kenneth Gaspar</componente>
            </componentes>
        </grupo>
        <grupo nombre="O'funk'illo" estilo="Funk Rock">
            <componentes>
                <componente instrumento="Voz">Andreas Lutz</componente>
                <componente instrumento="Bajo">Pepe Bao </componente>
                <componente instrumento="Guitarra">Javi Lynch Marssiano</componente>
            </componentes>
            <discos>
                <disco orden="1">O'Funk'illo</disco>
                <disco orden="2">En el Planeta Aseituna</disco>
                <disco orden="3">No te cabe na'</disco>
                <disco orden="4">Sesi√≥n Golfa</disco>
                <disco orden="5">5mentario</disco>
            </discos>
        </grupo>
    </grupos>
</discografica>
