=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.11 Creando XSD (1)/AG4.11_protectora_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Actividad 4.11
    Nombre:Albano
    Apellidos:Díez de Paulino
    Curso:DAMT1 2022/2023
    Fecha:06/02/2023-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Protectora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Perro" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DniPropietario" minOccurs="1" maxOccurs="3" type="dni" />
                            <xs:element name="Raza" minOccurs="0" maxOccurs="1" type="TipoRaza" />
                            <xs:element name="Kg" minOccurs="1" maxOccurs="1" type="TipoKg" />
                            <xs:element name="FechaNacimiento" minOccurs="1" maxOccurs="1" type="Date" />
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="TipoID" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TipoID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[P][0-9]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dni">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[A-Z]"></xs:pattern>
            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TipoRaza">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Compañía"></xs:enumeration>
            <xs:enumeration value="Pastor"></xs:enumeration>
            <xs:enumeration value="Caza"></xs:enumeration>
            <xs:enumeration value="Defensa"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TipoKg">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="100"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Date">
        <xs:restriction base="xs:date">
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/ACTIVIDADESGUIADAS/Actividad AG4.11 Creando XSD (1)/AG4.11_protectora.xml
<Protectora xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="AG4.11_protectora_XSD.xsd">
    <Perro id="P001">
        <DniPropietario>72727272A</DniPropietario>
        <Raza>Pastor</Raza>
        <Kg>45</Kg>
        <FechaNacimiento>2000-04-25</FechaNacimiento>
    </Perro> 
    <Perro id="P002">
        <DniPropietario>73737373A</DniPropietario>
        <Raza>Compañía</Raza>
        <Kg>10</Kg>
        <FechaNacimiento>2017-11-02</FechaNacimiento>
    </Perro>   
</Protectora>
