=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_5/almacen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Declaracion de elemento RAIZ-->
    <xs:element name="almacen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="empleados" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element ref="clientes" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element ref="pedidos" minOccurs="1" maxOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- Declaracion de claves primarias-->
        <xs:key name="pkoperario">
            <xs:selector xpath="almacen/empleados/operario" />
            <xs:field xpath="@numOpe" />
        </xs:key>
        <xs:key name="pkadministrador">
            <xs:selector xpath="almacen/empleados/administrativo" />
            <xs:field xpath="@numAdm" />
        </xs:key>
        <xs:key name="pkcliente">
            <xs:selector xpath="almacen/clientes/cliente" />
            <xs:field xpath="@numCli" />
        </xs:key>
        <xs:key name="pkpedido">
            <xs:selector xpath="./pedidos/pedido" />
            <xs:field xpath="@numPed" />
        </xs:key>
        <!-- Declaracion de claves forenea-->
        <xs:keyref name="fk_supervisor_operario" refer="pkoperario">
            <xs:selector xpath="almacen/empleados/operario" />
            <xs:field xpath="supervisor" />
        </xs:keyref>
        <xs:keyref name="fk_pedidos_operario" refer="pkoperario">
            <xs:selector xpath="almacen/pedidos/pedido" />
            <xs:field xpath="ope" />
        </xs:keyref>
        <xs:keyref name="fk_supervisor_administrador" refer="pkadministrador">
            <xs:selector xpath="almacen/empleados/administrativo" />
            <xs:field xpath="supervisor" />
        </xs:keyref>
        <xs:keyref name="fk_pedido_administrador" refer="pkadministrador">
            <xs:selector xpath="almacen/pedidos/pedido" />
            <xs:field xpath="adm" />
        </xs:keyref>
        <xs:keyref name="fk_pedido_clientes" refer="pkcliente">
            <xs:selector xpath="almacen/pedidos/pedido" />
            <xs:field xpath="cli" />
        </xs:keyref>
    </xs:element>

    <!-- Declaracion de elementos Hijos-->
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="operario" maxOccurs="unbounded"></xs:element>
                <xs:element ref="administrativo" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="operario">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="datos"></xs:group>
                <xs:element ref="fechaNac"></xs:element>
                <xs:element ref="fechaAlt"></xs:element>
                <xs:element name="antiguedad" type="xs:string" />
                <xs:choice>
                    <xs:element name="jefe" minOccurs="0">
                        <xs:complexType></xs:complexType>
                    </xs:element>
                    <xs:element name="supervisor" minOccurs="0" type="xs:string" />
                </xs:choice>
                <xs:choice>
                    <xs:element name="expedicion" minOccurs="0">
                        <xs:complexType></xs:complexType>
                    </xs:element>
                    <xs:element name="recepcion" minOccurs="0">
                        <xs:complexType></xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="numOpe" use="required" type="tiponumOpe" />
        </xs:complexType>
    </xs:element>
    <xs:element name="administrativo">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="datos"></xs:group>
                <xs:element ref="fechaNac"></xs:element>
                <xs:element ref="fechaAlt"></xs:element>
                <xs:element name="antiguedad" type="xs:string" />
                <xs:choice>
                    <xs:element name="jefe" minOccurs="0">
                        <xs:complexType></xs:complexType>
                    </xs:element>
                    <xs:element name="supervisor" minOccurs="0" type="xs:string" />
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="numAdm" use="required" type="tiponumAdm" />
        </xs:complexType>
    </xs:element>

    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="datos"></xs:group>
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="telefono" type="tipoTelefono" />
                        </xs:sequence>
                        <xs:attribute name="numCli" use="required" type="tiponumCli" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cli" type="xs:string" />
                            <xs:element name="adm" type="xs:string" />
                            <xs:element name="ope" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="total" type="tipoTotal" />
                        </xs:sequence>
                        <xs:attribute name="numPed" type="tiponumPed" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="datos">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="apellidos" type="xs:string" />
            <xs:element name="dni" type="tipoDNI" />
        </xs:sequence>
    </xs:group>

    <xs:group name="fecha">
        <xs:sequence>
            <xs:element name="dia" type="tipoDia" />
            <xs:element name="mes" type="tipoMes" />
            <xs:element name="anio" type="tipoAnio" />
        </xs:sequence>
    </xs:group>

    <xs:element name="fechaAlt">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="fecha"></xs:group>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fechaNac">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="fecha"></xs:group>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- Declaracion de Tipos-->

    <xs:simpleType name="tiponumOpe">
        <xs:restriction base="xs:string">
            <xs:pattern value="OP-[0-9][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tiponumAdm">
        <xs:restriction base="xs:string">
            <xs:pattern value="ADMIN[0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tiponumCli">
        <xs:restriction base="xs:string">
            <xs:pattern value="CLI\\[0-9]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tiponumPed">
        <xs:restriction base="xs:string">
            <xs:pattern value="(PED21.|PED22.)[0-9]{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTelefono">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[6|9][0-9]{8}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoTotal">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9][0-9]{2,3}[â‚¬]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoDNI">
        <xs:restriction base="xs:string">
            <xs:pattern value="[X]?[0-9]{8}[-][A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoDia">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="31"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoMes">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="12"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoAnio">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1950"></xs:minInclusive>
            <xs:maxInclusive value="2022"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_5/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="almacen.xsd">
    <empleados>
        <operario numOpe="OP-01">
            <nombre>Andres</nombre>
            <apellidos>Sanchez Sierra</apellidos>
            <dni>11085975-Z</dni>
            <fechaNac>
                <dia>8</dia>
                <mes>7</mes>
                <anio>1980</anio>
            </fechaNac>
            <fechaAlt>
                <dia>1</dia>
                <mes>1</mes>
                <anio>2000</anio>
            </fechaAlt>
            <antiguedad>22</antiguedad>
            <jefe />
        </operario>
        <operario numOpe="OP-02">
            <nombre>Alfonso</nombre>
            <apellidos>Dominguez Herrera</apellidos>
            <dni>X28987415-F</dni>
            <fechaNac>
                <dia>31</dia>
                <mes>1</mes>
                <anio>1995</anio>
            </fechaNac>
            <fechaAlt>
                <dia>25</dia>
                <mes>6</mes>
                <anio>2015</anio>
            </fechaAlt>
            <antiguedad>7</antiguedad>
            <supervisor>OP-01</supervisor>
            <expedicion />
        </operario>
        <operario numOpe="OP-03">
            <nombre>David</nombre>
            <apellidos>Narvaez Torres</apellidos>
            <dni>X65892147-S</dni>
            <fechaNac>
                <dia>17</dia>
                <mes>6</mes>
                <anio>1985</anio>
            </fechaNac>
            <fechaAlt>
                <dia>1</dia>
                <mes>3</mes>
                <anio>2018</anio>
            </fechaAlt>
            <antiguedad>4</antiguedad>
            <supervisor>OP-01</supervisor>
            <recepcion />
        </operario>
        <operario numOpe="OP-04">
            <nombre>Miguel</nombre>
            <apellidos>Diaz Fernandez</apellidos>
            <dni>87365285-G</dni>
            <fechaNac>
                <dia>8</dia>
                <mes>8</mes>
                <anio>1988</anio>
            </fechaNac>
            <fechaAlt>
                <dia>7</dia>
                <mes>12</mes>
                <anio>2009</anio>
            </fechaAlt>
            <antiguedad>13</antiguedad>
            <supervisor>OP-01</supervisor>
            <recepcion />
        </operario>
        <operario numOpe="OP-05">
            <nombre>Sara</nombre>
            <apellidos>Saez Sainz</apellidos>
            <dni>04592877-D</dni>
            <fechaNac>
                <dia>23</dia>
                <mes>12</mes>
                <anio>1991</anio>
            </fechaNac>
            <fechaAlt>
                <dia>18</dia>
                <mes>11</mes>
                <anio>2019</anio>
            </fechaAlt>
            <antiguedad>3</antiguedad>
            <supervisor>OP-01</supervisor>
            <expedicion />
        </operario>
        <administrativo numAdm="ADMIN1">
            <nombre>Cristina</nombre>
            <apellidos>Hernandez Perez</apellidos>
            <dni>52874681-H</dni>
            <fechaNac>
                <dia>12</dia>
                <mes>5</mes>
                <anio>1975</anio>
            </fechaNac>
            <fechaAlt>
                <dia>1</dia>
                <mes>1</mes>
                <anio>2000</anio>
            </fechaAlt>
            <antiguedad>22</antiguedad>
            <jefe />
        </administrativo>
        <administrativo numAdm="ADMIN2">
            <nombre>Pilar</nombre>
            <apellidos>Minguez Ortiz</apellidos>
            <dni>12345678-R</dni>
            <fechaNac>
                <dia>16</dia>
                <mes>10</mes>
                <anio>1986</anio>
            </fechaNac>
            <fechaAlt>
                <dia>3</dia>
                <mes>6</mes>
                <anio>2005</anio>
            </fechaAlt>
            <antiguedad>17</antiguedad>
            <supervisor>ADMIN1</supervisor>
        </administrativo>
        <administrativo numAdm="ADMIN3">
            <nombre>Javier</nombre>
            <apellidos>Salvo Diez</apellidos>
            <dni>87654312-D</dni>
            <fechaNac>
                <dia>29</dia>
                <mes>3</mes>
                <anio>1970</anio>
            </fechaNac>
            <fechaAlt>
                <dia>27</dia>
                <mes>9</mes>
                <anio>2010</anio>
            </fechaAlt>
            <antiguedad>12</antiguedad>
            <supervisor>ADMIN1</supervisor>
        </administrativo>
    </empleados>
    <clientes>
        <cliente numCli="CLI\001">
            <nombre>Jose Luis</nombre>
            <apellidos>Garcia Garcia</apellidos>
            <dni>58621489-T</dni>
            <direccion>c/ Mi calle, 15</direccion>
            <telefono>942000000</telefono>
        </cliente>
        <cliente numCli="CLI\002">
            <nombre>Juan Luis</nombre>
            <apellidos>Rodriguez Salmon</apellidos>
            <dni>12544473-F</dni>
            <direccion>c/ Tu calle, 56</direccion>
            <telefono>606606606</telefono>
        </cliente>
        <cliente numCli="CLI\003">
            <nombre>Maria Luisa</nombre>
            <apellidos>Hernandez Sandoval</apellidos>
            <dni>09985246-R</dni>
            <direccion>c/ Su calle, 3</direccion>
            <telefono>600888555</telefono>
        </cliente>
    </clientes>
    <pedidos>
        <pedido numPed="PED21.01">
            <cli>CLI\001</cli>
            <adm>ADMIN3</adm>
            <ope>OP-01</ope>
            <total>500€</total>
        </pedido>
        <pedido numPed="PED22.01">
            <cli>CLI\002</cli>
            <adm>ADMIN2</adm>
            <ope>OP-02</ope>
            <ope>OP-03</ope>
            <total>1500€</total>
        </pedido>
        <pedido numPed="PED22.02">
            <cli>CLI\003</cli>
            <adm>ADMIN1</adm>
            <ope>OP-01</ope>
            <ope>OP-04</ope>
            <ope>OP-05</ope>
            <total>5500€</total>
        </pedido>
    </pedidos>
</almacen>
