=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio1/Schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libro" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="autor" type="xs:string"></xs:element>
                <xs:element name="editorial" type="xs:string"></xs:element>
                <xs:element name="genero" type="xs:string"></xs:element>
                <xs:element name="fecha" type="xs:date"></xs:element>
                <xs:element name="valoracion" type="xs:unsignedInt" ></xs:element>
                <xs:element name="comentario" type="xs:string" minOccurs="0" maxOccurs="3" ></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/EjerciciosSchemas/Ejercicio1/libreria.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Schema.xsd">
    <libro>
        <nombre></nombre>
        <autor></autor>
        <editorial></editorial>
        <genero></genero>
        <fecha>1997-05-15</fecha>
        <valoracion>2</valoracion>
        <comentario></comentario>
    </libro>
</libreria>
