=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/EJERCICIO1/DTD/validador.dtd
<!ELEMENT agenda (propietario,contacto*)>
    <!ELEMENT propietario (nombre, apellido+, direccion,telefono+,email*)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
    <!ELEMENT contacto (id,nombre, apellido+, direccion, telefono+,email*)>
        <!ELEMENT id (#PCDATA)>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/DTD/EJERCICIO1/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE agenda SYSTEM "DTD/validador.dtd">
<agenda>
    <propietario>
        <nombre>Albano</nombre>
        <apellido>Diez</apellido>
        <apellido>Paulino</apellido>
        <direccion>Santo√±a</direccion>
        <telefono>666666666</telefono>
        <telefono>555555555</telefono>
        <email>hola@hola.es</email>
    </propietario>
    
    <contacto>
        <id>1</id>
        <nombre>Ramiro</nombre>
        <apellido>Gomez</apellido>
        <apellido>Gomez</apellido>
        <direccion>Santander</direccion>
        <telefono>444444444</telefono>
        <email>adios@adios.es</email>
        <email>educantabria@educantabria.es</email>
    </contacto>

    <contacto>
        <id>2</id>
        <nombre>Juan</nombre>
        <apellido>Perez</apellido>
        <apellido>Perez</apellido>
        <direccion>Perez</direccion>
        <telefono>333333333</telefono>
        <telefono>234567891</telefono>
        <email>email@email.com</email>
    </contacto>
</agenda>
