=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_4/Empresa_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Declaracion de Elementos Raiz-->
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="clientes"></xs:element>
                <xs:element ref="empleados"></xs:element>
                <xs:element ref="pedidos"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- Declaracion de claves primarias-->
        <xs:key name="pkcliente">
            <xs:selector xpath="empresa/clientes/cliente" />
            <xs:field xpath="@numCli" />
        </xs:key>
        <xs:key name="pkempleado">
            <xs:selector xpath="empresa/empleados/empleado" />
            <xs:field xpath="@numEmp" />
        </xs:key>
        <xs:key name="pkpedidos">
            <xs:selector xpath="empresa/pedidos/pedido" />
            <xs:field xpath="@numPed" />
        </xs:key>
        <!-- Declaracion de claves forenea-->

        <xs:keyref name="fkcliente" refer="pkcliente">
            <xs:selector xpath="empresa/pedidos/pedido" />
            <xs:field xpath="cliente" />
        </xs:keyref>

        <xs:keyref name="fkempleado" refer="pkempleado">
            <xs:selector xpath="empresa/pedidos/pedido" />
            <xs:field xpath="cliente" />
        </xs:keyref>


    </xs:element>

    <!-- Definir Elementos Hijos-->
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="datosPersonales"></xs:group>
                            <xs:element ref="direccion"></xs:element>
                            <xs:element name="vip" minOccurs="0">
                                <xs:complexType></xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numCli" use="required" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="datosPersonales"/>
                            <xs:element name="puesto" type="xs:string" />
                            <xs:element name="antiguedad" type="tipoAntiguedad" />
                            <xs:element name="salario" type="tipoMoneda" />
                        </xs:sequence>
                        <xs:attribute name="numEmp" use="required" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" type="xs:string" />
                            <xs:element name="empleado" type="xs:string" />
                            <xs:element name="importe" type="tipoMoneda" />
                        </xs:sequence>
                        <xs:attribute name="numPed" use="required" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Declarar elemento complejo DatosPersonales y Direccion-->
    <xs:group name="datosPersonales">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="apellidos" type="xs:string" />
            <xs:element name="dni" type="tipoDNI" />
            <xs:element name="telefono" type="tipoTelofono" />
        </xs:sequence>
    </xs:group>

    <xs:element name="direccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="calle" type="xs:string" />
                <xs:element name="portal" type="xs:positiveInteger" />
                <xs:element name="piso" type="xs:positiveInteger" />
                <xs:element name="letra" type="tipoLetra" />
                <xs:element name="cp" type="tipoCp" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Declaracion de Tipos-->

    <xs:simpleType name="tipoDNI">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[-][A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTelofono">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[6|9][0-9]{8}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoMoneda">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3,4}[â‚¬]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoLetra">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoCp">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{5}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoAntiguedad">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="99"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== ducatona/DAM/DAM-1/LMSG/2-EVALUACION/TEMA-4 DTD-SXD/SCHEMAS/Tareas/Tarea4_4/Empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Empresa_XSD.xsd">
    <clientes>
        <cliente numCli="C1">
            <nombre>Andres</nombre>
            <apellidos>Perez Lopez</apellidos>
            <dni>11111111-A</dni>
            <telefono>942942942</telefono>
            <direccion>
                <calle>C/ La salida</calle>
                <portal>85</portal>
                <piso>9</piso>
                <letra>Z</letra>
                <cp>39985</cp>
            </direccion>
        </cliente>
        <cliente numCli="C2">
            <nombre>Paula</nombre>
            <apellidos>Sanchez Jimenez</apellidos>
            <dni>22222222-B</dni>
            <telefono>942987997</telefono>
            <direccion>
                <calle>C/ La entrada</calle>
                <portal>1</portal>
                <piso>5</piso>
                <letra>G</letra>
                <cp>39001</cp>
            </direccion>
        </cliente>
        <cliente numCli="C3">
            <nombre>Cristina</nombre>
            <apellidos>Rodriguez Fernandez</apellidos>
            <dni>33333333-C</dni>
            <telefono>942123123</telefono>
            <direccion>
                <calle>C/ Del medio</calle>
                <portal>9</portal>
                <piso>4</piso>
                <letra>H</letra>
                <cp>39600</cp>
            </direccion>
            <vip />
        </cliente>
    </clientes>
    <empleados>
        <empleado numEmp="E1">
            <nombre>Juan Jose</nombre>
            <apellidos>Martinez Cuevas</apellidos>
            <dni>44444444-D</dni>
            <telefono>942556987</telefono>
            <puesto>Responsable de ventas</puesto>
            <antiguedad>10</antiguedad>
            <salario>3500€</salario>
        </empleado>
        <empleado numEmp="E2">
            <nombre>Nuria</nombre>
            <apellidos>Hernandez Arce</apellidos>
            <dni>55555555-E</dni>
            <telefono>942159753</telefono>
            <puesto>Comercial</puesto>
            <antiguedad>2</antiguedad>
            <salario>900€</salario>
        </empleado>
    </empleados>
    <pedidos>
        <pedido numPed="P1">
            <cliente>C1</cliente>
            <empleado>E1</empleado>
            <importe>300€</importe>
        </pedido>
        <pedido numPed="P2">
            <cliente>C2</cliente>
            <empleado>E1</empleado>
            <importe>400€</importe>
        </pedido>
        <pedido numPed="P3">
            <cliente>C3</cliente>
            <empleado>E1</empleado>
            <importe>3000€</importe>
        </pedido>
        <pedido numPed="P4">
            <cliente>C1</cliente>
            <empleado>E2</empleado>
            <importe>5000€</importe>
        </pedido>
        <pedido numPed="P5">
            <cliente>C2</cliente>
            <empleado>E2</empleado>
            <importe>450€</importe>
        </pedido>
    </pedidos>
</empresa>
